### ISSUE TITLE
Composer installs old version of this SDK

### ISSUE THREAD

**Issue by simaranjit** [intuit/QuickBooks-V3-PHP-SDK#230] opened 2019-06-10 07:30 UTC
Hi,

I have installed this SDK using composer
`composer require quickbooks/v3-php-sdk` and `5.0.4` is the current stable version, but if I compare it with the master on GitHub, code is different.

For example, compare this file:
`src/Core/HttpClients/CurlHttpClient.php`

Master contains this method:
```
private function setSSL(&$curl_opt, $verifySSL){
      $tlsVersion = $this->basecURL->versionOfTLS();
      $versions = ['TLS 1.2', 'TLS 1.3'];
      if(! in_array($tlsVersion, $versions)){
          throw new SdkException("Error. Checking TLS 1.2/1.3 version failed. Please make sure your PHP cURL supports TSL 1.2/1.3");
      }
      if($verifySSL){
          $curl_opt[CURLOPT_SSL_VERIFYPEER] = true;
          $curl_opt[CURLOPT_SSL_VERIFYHOST] = 2;
          //based on spec, if TSL 1.2 is supported, it will use the TLS 1.2 or latest version by default
          //$curl_opt[CURLOPT_SSLVERSION] = 6;
          $curl_opt[CURLOPT_CAINFO] = CoreConstants::getCertPath(); //Pem certification Key Path
      }
    }
```

Composer package composer contains this method
```
private function setSSL(&$curl_opt, $verifySSL){
      $tlsVersion = $this->basecURL->versionOfTLS();
      if(strcmp($tlsVersion, "TLS 1.2") != 0){
          throw new SdkException("Error. Checking TLS 1.2 version failed. Please make sure your PHP cURL supports TSL 1.2");
      }
      if($verifySSL){
          $curl_opt[CURLOPT_SSL_VERIFYPEER] = true;
          $curl_opt[CURLOPT_SSL_VERIFYHOST] = 2;
          //based on spec, if TSL 1.2 is supported, it will use the TLS 1.2 or latest version by default
          //$curl_opt[CURLOPT_SSLVERSION] = 6;
          $curl_opt[CURLOPT_CAINFO] = CoreConstants::getCertPath(); //Pem certification Key Path
      }
    }
```

Please update composer package on priority, we're facing issues due to this.

**Comment by simaranjit** [comment] 2019-06-11 10:44
@hlu2 ca you fix it on priority?

**Comment by it-all** [comment] 2019-06-26 15:31
@simaranjit I think the changes you reference are from a commit since 5.0.4: https://github.com/intuit/QuickBooks-V3-PHP-SDK/compare/5.0.4...master

But, it seems composer may be installing v5.0.3. I updated composer.json to "quickbooks/v3-php-sdk": "^5.0.4" and ran composer update and it worked.

**Comment by CloudCui** [comment] 2019-07-09 00:35
@it-all your solution didn't work for me.

The tag for 5.0.4 is `5.0.4` instead of `v5.0.4`, unsure if that was the cause. @hlu2

**Comment by it-all** [comment] 2019-07-09 12:11
@CloudCui not sure why.

My composer.json has:

```
"quickbooks/v3-php-sdk": "^5.0.4"
```

And running composer show gives: 
```
quickbooks/v3-php-sdk               5.0.4    The Official PHP SDK for QuickBooks Online Accounting API
```

**Comment by CloudCui** [comment] 2019-07-09 23:43
@it-all I tried again and _composer show_ gave me `5.0.4` as well but the `setSSL` method isn't actually the same as what's on `master` branch, unsure why

**Comment by CloudCui** [comment] 2019-07-10 00:42
The fix was merged to master in https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/209, which was after 5.0.4 was tagged.

A new tag needs to be created to include the fix.

cc @hlu2 @it-all

**Comment by aknosis** [comment] 2019-07-16 21:39
I had the same issue with TLS 1.3, I had to use `dev-master` instead of `^5.0`

**Comment by hlu2** [comment] 2019-07-23 21:57
This has been fixed.

**Closed by hlu2** 2019-07-23 21:57 UTC
