### ISSUE TITLE
Allow changing the timeout

### ISSUE THREAD

**Issue by kkmuffme** [intuit/QuickBooks-V3-PHP-SDK#310] opened 2020-05-01 11:55 UTC
```
cURL error during making API call. cURL Error Number:[28] with error:[Operation timed out after 10000 milliseconds with 0 out of 0 bytes received]
```

We'd like to be able to increase the timeout to 30 seconds to avoid these errors if the QBO servers are overloaded & slow to response or when requesting a lot of data.

In Java SDK this can be modified, but in PHP SDK there is no option for it.

Can you please add it, maybe in the style of setMinorVersion (=> setRequestTimeout)?

**Comment by bsivalingam** [comment] 2020-05-02 06:48
@kkmuffme that would be a great addition. Thanks for bringing it up, feel free to send in a PR if it is urgent. I will add it to our backlog.

**Comment by kkmuffme** [comment] 2020-05-02 09:31
Just to add for reference via: https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/java/configuration#default-values

BOTH values need to be customisable, however using a default value of 10 (instead of 0), since we want a default timeout in PHP:
connectionTimeout: 0 (or no value) implies no timeout is set. 
requestTimeout: 0 (or no value) implies no timeout is set.

**Comment by alexjeen** [comment] 2020-05-02 18:42
Hi guys,

Also probably fixed in this PR:
https://github.com/intuit/QuickBooks-V3-PHP-SDK/pull/311

Currently, the connect timeout was set lower to ten seconds.
On sandboxes this can cause issues.

Now its set to a default of 100 seconds, which is aligned with the non-passing of that parameter in all the functions using it.

**Comment by bsivalingam** [comment] 2020-05-14 05:14
@kkmuffme  as @alexjeen mentioned this will be solved for when we merge the PR.

**Closed by bsivalingam** 2020-05-14 05:14 UTC

**Comment by yii2backendwebdeveloper** [comment] 2020-10-02 15:32
We require this change as sometimes getting invoices throw this error which can create problem in production servers. 
BTW if the issue is closed then can anyone tell which parameter to set to achieve this timeout . 

I did not able to find it in the **documentation** it has not been updated yet
