### ISSUE TITLE
Fetch GST Overdue

### ISSUE THREAD

**Issue by jasminder** [intuit/QuickBooks-V3-PHP-SDK#299] opened 2020-03-22 17:19 UTC
I have tried general ledger and other reports available with SDK but not response doesnt include "this financial quarter to date" GST overdue stats. Please guide.

**Comment by bsivalingam** [comment] 2020-03-25 18:12
@jasminder Can you please specify which report you are expecting to see the financial quarter to date payload? Here is the list of report entities and the result payload examples: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/report-entities/accountlistdetail. If there is a report you are able to fetch from the UI and not via the API please let me know the specifics. Thanks!

**Comment by bsivalingam** [comment] 2020-05-14 18:50
@jasminder If the issue is still not resolved can you please create a support ticket at https://help.developer.intuit.com/s/. Closing the issue since it is not specific to the SDK.

**Closed by bsivalingam** 2020-05-14 18:50 UTC
