### ISSUE TITLE
Getting Property NameValue does not exist. Class IPPIntuitAnyType exception 

### ISSUE THREAD

**Issue by abhilashwebnapp** [intuit/QuickBooks-V3-PHP-SDK#352] opened 2020-08-28 14:52 UTC
@bsivalingam  While creating the payment using sample code https://github.com/IntuitDeveloper/SampleApp-CRUD-PHP/blob/master/CRUD_Examples/Payment/PaymentCreate.php we got the following error:::

`Property NameValue does not exist. Class IPPIntuitAnyType`

Payment is successfully created in qbo online but seems some issue while parsing response from sdk... 
This the response we getting from qbo after payment creation....

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2020-08-28T07:30:55.013-07:00">
  <Payment domain="QBO" sparse="false">
    <Id>28</Id>
    <SyncToken>0</SyncToken>
    <MetaData>
      <CreateTime>2020-08-28T07:30:55-07:00</CreateTime>
      <LastUpdatedTime>2020-08-28T07:30:55-07:00</LastUpdatedTime>
    </MetaData>
    <TxnDate>2020-08-28</TxnDate>
    <CurrencyRef name="United States Dollar">USD</CurrencyRef>
    <Line>
      <Amount>1.00</Amount>
      <LinkedTxn>
        <TxnId>8</TxnId>
        <TxnType>Invoice</TxnType>
      </LinkedTxn>
      <LineEx>
        <NameValue>
          <Name>txnId</Name>
          <Value>8</Value>
        </NameValue>
        <NameValue>
          <Name>txnOpenBalance</Name>
          <Value>206.84</Value>
        </NameValue>
        <NameValue>
          <Name>txnReferenceNumber</Name>
          <Value>1032</Value>
        </NameValue>
      </LineEx>
    </Line>
    <CustomerRef name="Dianna Bechtelar">5</CustomerRef>
    <DepositToAccountRef>31</DepositToAccountRef>
    <TotalAmt>1.00</TotalAmt>
    <UnappliedAmt>0</UnappliedAmt>
    <ProcessPayment>false</ProcessPayment>
  </Payment>
</IntuitResponse>`

**Comment by abisalehalliprasan** [comment] 2020-08-28 23:16
@abhilashwebnapp : we will check and get back to you. What version of the SDK are you using?

**Comment by abhilashwebnapp** [comment] 2020-08-29 02:34
@abisalehalliprasan we are using latest version of sdk .i.e 5.4

**Comment by abisalehalliprasan** [comment] 2020-09-03 03:19
@abhilashwebnapp : I tested with the latest version [5.4.3](https://github.com/intuit/QuickBooks-V3-PHP-SDK/tree/5.4.3) and I can successfully capture payment on an invoice. Below is my payload used in the script 

```
$theResourceObj = Payment::create([
    "CustomerRef" =>
        [
            "value" => "1"
        ],
    "PaymentMethodRef" => [
            "value" => "1"
        ],
    "DepositToAccountRef" => [
            "value" => "32"
        ],
    "TotalAmt" => 102.00,
    "Line" => [
        [
            "Amount" => 102.00,
            "LinkedTxn" => [
                [
                    "TxnId" => "30",
                    "TxnType" => "Invoice"
                ]]
        ]]
]);
$resultingObj = $dataService->Add($theResourceObj);
$error = $dataService->getLastError();

if ($error) {
    echo "The Status code is: " . $error->getHttpStatusCode() . "\n";
    echo "The Helper message is: " . $error->getOAuthHelperError() . "\n";
    echo "The Response message is: " . $error->getResponseBody() . "\n";
}
else {
    echo "Created Id={$resultingObj->Id}. Reconstructed response body:\n\n";
    $xmlBody = XmlObjectSerializer::getPostXmlFromArbitraryEntity($resultingObj, $urlResource);
    echo $xmlBody . "\n";
}
```

Response from SDK : 
```
<?xml version="1.0" encoding="UTF-8"?>
<ns0:Payment xmlns:ns0="http://schema.intuit.com/finance/v3">
  <ns0:Id>39</ns0:Id>
  <ns0:SyncToken>0</ns0:SyncToken>
  <ns0:MetaData>
    <ns0:CreateTime>2020-09-02T20:15:13-07:00</ns0:CreateTime>
    <ns0:LastUpdatedTime>2020-09-02T20:15:13-07:00</ns0:LastUpdatedTime>
  </ns0:MetaData>
  <ns0:TxnDate>2020-09-02</ns0:TxnDate>
  <ns0:CurrencyRef>USD</ns0:CurrencyRef>
  <ns0:Line>
    <ns0:Amount>102.00</ns0:Amount>
    <ns0:LinkedTxn>
      <ns0:TxnId>30</ns0:TxnId>
      <ns0:TxnType>Invoice</ns0:TxnType>
    </ns0:LinkedTxn>
    <ns0:LineEx/>
  </ns0:Line>
  <ns0:CustomerRef>1</ns0:CustomerRef>
  <ns0:DepositToAccountRef>32</ns0:DepositToAccountRef>
  <ns0:PaymentMethodRef>1</ns0:PaymentMethodRef>
  <ns0:TotalAmt>102.00</ns0:TotalAmt>
  <ns0:UnappliedAmt>0</ns0:UnappliedAmt>
  <ns0:ProcessPayment>false</ns0:ProcessPayment>
</ns0:Payment>
```
Could you provide your request payload if you are still seeing the error?

**Comment by abhilashwebnapp** [comment] 2020-09-03 12:22
@abisalehalliprasan We are still getting the error here is our payload 

```
$qboPayment = [
            'CustomerRef' => [
                'value' => '11'
            ],
            'Line' => [
                [
                    'Amount' => 1.00,
                    'LinkedTxn' => [
                        [
                            'TxnId' => '32',
                            'TxnType' => 'Invoice'
                        ]
                    ]
                ],
            ],
            'TotalAmt' => 1.00,
        ];
```

**Comment by abisalehalliprasan** [comment] 2020-09-03 23:51
@abhilashwebnapp : Tried using your request payload : 

```
// Add a customer
$paymentObj = Payment::create([
    'CustomerRef' => [
        'value' => '1'
    ],
    'Line' => [
        [
            'Amount' => 100.00,
            'LinkedTxn' => [
                [
                    'TxnId' => '21',
                    'TxnType' => 'Invoice'
                ]
            ]
        ],
    ],
    'TotalAmt' => 100.00,
]);

$resultingPaymentObj = $dataService->Add($paymentObj);
$error = $dataService->getLastError();
if ($error) {
    echo "The Status code is: " . $error->getHttpStatusCode() . "\n";
    echo "The Helper message is: " . $error->getOAuthHelperError() . "\n";
    echo "The Response message is: " . $error->getResponseBody() . "\n";
} else {
    echo "Created Id={$resultingPaymentObj->Id}. Reconstructed response body:\n\n";
    $xmlBody = XmlObjectSerializer::getPostXmlFromArbitraryEntity($resultingPaymentObj, $urlResource);
    echo $xmlBody . "\n";
}
```
Below is the response: 
```
<?xml version="1.0" encoding="UTF-8"?>
<ns0:Payment xmlns:ns0="http://schema.intuit.com/finance/v3">
  <ns0:Id>42</ns0:Id>
  <ns0:SyncToken>0</ns0:SyncToken>
  <ns0:MetaData>
    <ns0:CreateTime>2020-09-03T16:48:43-07:00</ns0:CreateTime>
    <ns0:LastUpdatedTime>2020-09-03T16:48:43-07:00</ns0:LastUpdatedTime>
  </ns0:MetaData>
  <ns0:TxnDate>2020-09-03</ns0:TxnDate>
  <ns0:CurrencyRef>USD</ns0:CurrencyRef>
  <ns0:Line>
    <ns0:Amount>100.00</ns0:Amount>
    <ns0:LinkedTxn>
      <ns0:TxnId>21</ns0:TxnId>
      <ns0:TxnType>Invoice</ns0:TxnType>
    </ns0:LinkedTxn>
    <ns0:LineEx/>
  </ns0:Line>
  <ns0:CustomerRef>1</ns0:CustomerRef>
  <ns0:DepositToAccountRef>32</ns0:DepositToAccountRef>
  <ns0:TotalAmt>100.00</ns0:TotalAmt>
  <ns0:UnappliedAmt>0</ns0:UnappliedAmt>
  <ns0:ProcessPayment>false</ns0:ProcessPayment>
</ns0:Payment>
```
I am getting back the `<LineEx>` fields as well. Make sure you are passing the correct payload. Will close this as not a bug for now.

**Closed by abisalehalliprasan** 2020-09-03 23:51 UTC

**Comment by abhilashwebnapp** [comment] 2020-09-04 07:03
@abisalehalliprasan Hmm that is interesting, the reason it not being replicated at your end I guess is bcoz your <LineEx /> doesn't seems to have any data inside it ...

**Comment by abhilashwebnapp** [comment] 2020-09-04 07:20
Anyway I fixed my issue by adding
in ```vendor/quickbooks/v3-php-sdk/src/Data/IPPIntuitAnyType.php```

```
/**
     * @Definition Any other preference not covered in base is
    covered as name value pair, for detailed explanation look at the
    document
     * @xmlType element
     * @xmlNamespace http://schema.intuit.com/finance/v3
     * @xmlMinOccurs 0
     * @xmlMaxOccurs unbounded
     * @xmlName NameValue
     * @var com\intuit\schema\finance\v3\IPPNameValue
     */
    public $NameValue;
```
